#!/usr/bin/env bash

declare basedir
basedir="$( cd "$( dirname $0 )" && pwd )"
readonly basedir

declare sourcedir
sourcedir="$1"
readonly sourcedir

if [ "${sourcedir}" == "" ] ; then
  echo "usage: ${0##*/} <source directory>"
  exit 0
fi

if [ ! -d "${sourcedir}" ] ; then
  echo "'${sourcedir}' is not a directory."
  exit 0
fi

echo "terraforming directory '${sourcedir}'.."

# copy files 
rsync -auv ${sourcedir}/.bashrc ${basedir}
rsync -auv ${sourcedir}/.bash_aliases ${basedir}
rsync -auv ${sourcedir}/.bash_colours ${basedir}
rsync -auv ${sourcedir}/.bash_login ${basedir}
rsync -auv ${sourcedir}/.bash_logout ${basedir}
rsync -auv ${sourcedir}/.bash_profile ${basedir}
rsync -auv ${sourcedir}/.gitconfig ${basedir}
rsync -auv ${sourcedir}/.gitignore ${basedir}
rsync -auv ${sourcedir}/.gvimrc ${basedir}
rsync -auv ${sourcedir}/.inputrc ${basedir}
rsync -auv ${sourcedir}/.profile ${basedir}
rsync -auv ${sourcedir}/.vim ${basedir}
rsync -auv ${sourcedir}/.vimrc ${basedir}

