#!/usr/bin/env bash

declare basedir
basedir="$( cd "$( dirname $0 )" && pwd )"
readonly basedir

declare targetdir
targetdir="$1"
readonly targetdir

if [ "${targetdir}" == "" ] ; then
  echo "usage: ${0##*/} <target directory>"
  exit 0
fi

if [ ! -d "${targetdir}" ] ; then
  echo "'${targetdir}' is not a directory."
  exit 0
fi

echo "terraforming directory '${targetdir}'.."

# sync files 
rsync -auv ${basedir}/.bashrc ${targetdir}
rsync -auv ${basedir}/.bash_aliases ${targetdir}
rsync -auv ${basedir}/.bash_colours ${targetdir}
rsync -auv ${basedir}/.bash_login ${targetdir}
rsync -auv ${basedir}/.bash_logout ${targetdir}
rsync -auv ${basedir}/.bash_profile ${targetdir}
rsync -auv ${basedir}/.gitconfig ${targetdir}
rsync -auv ${basedir}/.gitignore ${targetdir}
rsync -auv ${basedir}/.gvimrc ${targetdir}
rsync -auv ${basedir}/.inputrc ${targetdir}
rsync -auv ${basedir}/.profile ${targetdir}
rsync -auv ${basedir}/.vim ${targetdir}
rsync -auv ${basedir}/.vimrc ${targetdir}

