#!/usr/bin/env bash

declare basedir
basedir="$( cd "$( dirname $0 )" && pwd )"
readonly basedir

declare targetdir
targetdir="$1"
readonly targetdir

if [ "${targetdir}" == "" ] ; then
  echo "usage: ${0##*/} <target directory>"
  exit 0
fi

if [ ! -d "${targetdir}" ] ; then
  echo "'${targetdir}' is not a directory."
  exit 0
fi

echo "terraforming directory '${targetdir}'.."

# sync files

filelist=$(
  find ${basedir} -name 'sync-to' -o -name 'sync-from' -o -name '*.git*' -a -prune -o -print \
    | sort | sed "s|^${basedir}/||g;"
)

for f in ${filelist} ; do
  rsync -auv ${basedir}/${f} ${targetdir}/$( dirname ${f} )/
done

